"""Futures paper trading module for Fixelnet signals."""
from .futures_strategy import (
    LONG, HEAVY_SHORT, HOLD,
    SIGNAL_NAMES,
    FuturesOrderParams,
    signal_to_futures_order,
)
from .futures_risk import (
    BASE_NOTIONAL_USD,
    HEAVY_SHORT_MULTIPLIER,
    MAX_OPEN_POSITIONS,
    STOP_LOSS_PCT,
    MIN_CONFIDENCE,
    FuturesRiskCheck,
    check_futures_risk,
    compute_stop_loss,
    notional_for_signal,
)
from .futures_simulator import (
    load_futures_trades,
    load_open_futures_trades,
    record_futures_trade,
    close_futures_trade,
    close_open_on_hold,
    mark_to_market_futures,
    get_futures_summary,
    send_futures_weekly_if_due,
)
from .futures_notify import (
    send,
    notify_futures_trade_entered,
    notify_futures_trade_closed,
    notify_futures_hold_close,
    notify_futures_no_trade,
    notify_futures_mtm,
    notify_futures_weekly_summary,
    notify_error,
)

__all__ = [
    "LONG", "HEAVY_SHORT", "HOLD",
    "SIGNAL_NAMES",
    "FuturesOrderParams",
    "signal_to_futures_order",
    "BASE_NOTIONAL_USD",
    "HEAVY_SHORT_MULTIPLIER",
    "MAX_OPEN_POSITIONS",
    "STOP_LOSS_PCT",
    "MIN_CONFIDENCE",
    "FuturesRiskCheck",
    "check_futures_risk",
    "compute_stop_loss",
    "notional_for_signal",
    "load_futures_trades",
    "load_open_futures_trades",
    "record_futures_trade",
    "close_futures_trade",
    "close_open_on_hold",
    "mark_to_market_futures",
    "get_futures_summary",
    "send_futures_weekly_if_due",
    "send",
    "notify_futures_trade_entered",
    "notify_futures_trade_closed",
    "notify_futures_hold_close",
    "notify_futures_no_trade",
    "notify_futures_mtm",
    "notify_futures_weekly_summary",
    "notify_error",
]
